-- database/init.sql

-- 1. CLEANUP (Reset the state)
DROP TABLE IF EXISTS adjudication_value_codes;
DROP TABLE IF EXISTS claim_adjustment_group_codes;
DROP TABLE IF EXISTS carc_codes;
DROP TABLE IF EXISTS rarc_codes;

-- 2. CREATE TABLES

-- Value Codes (What is this dollar amount?)
CREATE TABLE adjudication_value_codes (
    code VARCHAR(50) PRIMARY KEY,
    display VARCHAR(255),
    definition TEXT
);

-- Group Codes (Who is financially responsible?)
CREATE TABLE claim_adjustment_group_codes (
    code VARCHAR(10) PRIMARY KEY,
    description VARCHAR(255),
    responsibility TEXT,
    start_date DATE
);

-- CARC Codes (Why was it adjusted?)
CREATE TABLE carc_codes (
    code VARCHAR(10) PRIMARY KEY,
    description TEXT,
    action_hint TEXT,
    start_date DATE
);

-- RARC Codes (Specific details)
CREATE TABLE rarc_codes (
    code VARCHAR(10) PRIMARY KEY,
    description TEXT,
    start_date DATE
);

-- 3. SEED DATA (Exact Column Match)

-- Insert Value Codes
INSERT INTO adjudication_value_codes (code, display, definition) VALUES
('submitted', 'Submitted Amount', 'The total submitted amount for the claim or group or line item.'),
('copay', 'CoPay', 'Patient Co-Payment'),
('eligible', 'Eligible Amount', 'Amount of the change which is considered for adjudication.'),
('deductible', 'Deductible', 'Amount deducted from the eligible amount prior to adjudication.'),
('unallocdeduct', 'Unallocated Deductible', 'The amount of deductible which could not allocated to other line items.'),
('eligpercent', 'Eligible %', 'Eligible Percentage.'),
('tax', 'Tax', 'The amount of tax.'),
('benefit', 'Benefit Amount', 'Amount payable under the coverage');

-- Insert Group Codes
INSERT INTO claim_adjustment_group_codes (code, description, responsibility, start_date) VALUES
('CO', 'Contractual Obligation', 'Contractual', '05/20/2018'),
('OA', 'Other Adjustment', 'Other', '05/20/2018'),
('PI', 'Payor Initiated Reduction', 'Payor', '05/20/2018'),
('PR', 'Patient Responsibility', 'Patient', '05/20/2018');

-- Insert CARC Codes (The Rules)
INSERT INTO carc_codes (code, description, action_hint, start_date) VALUES
('1', 'Deductible Amount', 'Collect deductible from patient.', '1995-01-01'),
('2', 'Coinsurance Amount', 'Collect coinsurance from patient.', '1995-01-01'),
('3', 'Co-payment Amount', 'Collect co-pay from patient.', '1995-01-01'),
('4', 'The procedure code is inconsistent with the modifier used.', 'Review coding. Correct modifier and resubmit.', '1995-01-01'),
('5', 'The procedure code/type of bill is inconsistent with the place of service.', 'Review coding. Correct Place of Service and resubmit.', '1995-01-01'),
('6', 'The procedure/revenue code is inconsistent with the patient''s age.', 'Verify patient DOB and CPT restrictions. Correct and resubmit.', '1995-01-01'),
('7', 'The procedure/revenue code is inconsistent with the patient''s gender.', 'Verify patient gender and CPT restrictions. Correct and resubmit.', '1995-01-01'),
('8', 'The procedure code is inconsistent with the provider type/specialty (taxonomy).', 'Verify provider taxonomy code on claim. Resubmit.', '1995-01-01'),
('9', 'The diagnosis is inconsistent with the patient''s age.', 'Verify diagnosis code age limits. Correct and resubmit.', '1995-01-01'),
('10', 'The diagnosis is inconsistent with the patient''s gender.', 'Verify diagnosis code gender limits. Correct and resubmit.', '1995-01-01'),
('11', 'The diagnosis is inconsistent with the procedure.', 'Check Medical Necessity/LCD. Correct diagnosis if applicable and resubmit.', '1995-01-01'),
('12', 'The diagnosis is inconsistent with the provider type.', 'Verify diagnosis against provider specialty. Resubmit.', '1995-01-01'),
('13', 'The date of death precedes the date of service.', 'Verify patient date of death and service dates. Correct error.', '1995-01-01'),
('14', 'The date of birth follows the date of service.', 'Verify patient DOB. Correct error.', '1995-01-01'),
('16', 'Claim/service lacks information or has submission/billing error(s).', 'Review remarks/rejection codes. Add missing info and resubmit.', '1995-01-01'),
('18', 'Exact duplicate claim/service', 'Check for prior payment. Void if true duplicate; Appeal with notes if distinct service.', '1995-01-01'),
('19', 'This is a work-related injury/illness and thus the liability of the Worker''s Compensation Carrier.', 'Bill Worker''s Comp carrier. Do not bill health plan.', '1995-01-01'),
('20', 'This injury/illness is covered by the liability carrier.', 'Bill Liability/Auto carrier. Do not bill health plan.', '1995-01-01'),
('21', 'This injury/illness is the liability of the no-fault carrier.', 'Bill No-Fault carrier. Do not bill health plan.', '1995-01-01'),
('22', 'This care may be covered by another payer per coordination of benefits.', 'Identify primary payer. Bill primary or send EOB to secondary.', '1995-01-01'),
('23', 'The impact of prior payer(s) adjudication including payments and/or adjustments.', 'Post adjustment based on primary payer EOB.', '1995-01-01'),
('24', 'Charges are covered under a capitation agreement/managed care plan.', 'Write off balance. Do not bill patient.', '1995-01-01'),
('26', 'Expenses incurred prior to coverage.', 'Verify eligibility dates. Bill patient if truly not covered.', '1995-01-01'),
('27', 'Expenses incurred after coverage terminated.', 'Verify eligibility dates. Bill patient if truly not covered.', '1995-01-01'),
('29', 'The time limit for filing has expired.', 'Write off (if contracted). Appeal with proof of timely filing if available.', '1995-01-01'),
('31', 'Patient cannot be identified as our insured.', 'Verify Member ID and demographics. Correct and resubmit.', '1995-01-01'),
('32', 'Our records indicate the patient is not an eligible dependent.', 'Verify dependency status. Bill patient if ineligible.', '1995-01-01'),
('33', 'Insured has no dependent coverage.', 'Verify plan coverage. Bill patient.', '1995-01-01'),
('34', 'Insured has no coverage for newborns.', 'Verify plan coverage. Bill patient.', '1995-01-01'),
('35', 'Lifetime benefit maximum has been reached.', 'Bill patient for non-covered amount.', '1995-01-01'),
('39', 'Services denied at the time authorization/pre-certification was requested.', 'Appeal with medical necessity or write off.', '1995-01-01'),
('40', 'Charges do not meet qualifications for emergent/urgent care.', 'Appeal with ER records proving urgency or bill patient.', '1995-01-01'),
('44', 'Prompt-pay discount.', 'Write off (Contractual Adjustment).', '1995-01-01'),
('45', 'Charge exceeds fee schedule/maximum allowable or contracted/legislated fee arrangement.', 'Write off difference. DO NOT bill patient.', '1995-01-01'),
('49', 'This is a non-covered service because it is a routine/preventive exam.', 'Bill patient (if policy allows) or write off.', '1995-01-01'),
('50', 'These are non-covered services because this is not deemed a ''medical necessity'' by the payer.', 'Review records. Appeal with documentation or write off (bill patient only if ABN signed).', '1995-01-01'),
('51', 'These are non-covered services because this is a pre-existing condition.', 'Verify plan start date and laws. Bill patient if valid.', '1995-01-01'),
('53', 'Services by an immediate relative or a member of the same household are not covered.', 'Bill patient.', '1995-01-01'),
('54', 'Multiple physicians/assistants are not covered in this case.', 'Write off or Appeal if medical necessity dictates multiple providers.', '1995-01-01'),
('55', 'Procedure/treatment/drug is deemed experimental/investigational by the payer.', 'Bill patient (if notified prior) or write off.', '1995-01-01'),
('56', 'Procedure/treatment has not been deemed ''proven to be effective'' by the payer.', 'Bill patient (if notified prior) or write off.', '1995-01-01'),
('58', 'Treatment was deemed by the payer to have been rendered in an inappropriate or invalid place of service.', 'Correct Place of Service code and resubmit.', '1995-01-01'),
('59', 'Processed based on multiple or concurrent procedure rules.', 'Write off (Bundling/MPPR rule). Do not bill patient.', '1995-01-01'),
('60', 'Charges for outpatient services are not covered when performed within a period of time prior to or after inpatient services.', 'Write off (Bundled into IP stay).', '1995-01-01'),
('61', 'Adjusted for failure to obtain second surgical opinion', 'Write off (Provider liability usually).', '1995-01-01'),
('66', 'Blood Deductible.', 'Collect blood deductible from patient.', '1995-01-01'),
('69', 'Day outlier amount.', 'Informational adjustment.', '1995-01-01'),
('70', 'Cost outlier - Adjustment to compensate for additional costs.', 'Post payment increase.', '1995-01-01'),
('74', 'Indirect Medical Education Adjustment.', 'Post adjustment (Instructional).', '1995-01-01'),
('75', 'Direct Medical Education Adjustment.', 'Post adjustment (Instructional).', '1995-01-01'),
('76', 'Disproportionate Share Adjustment.', 'Post adjustment (DSH).', '1995-01-01'),
('78', 'Non-Covered days/Room charge adjustment.', 'Bill patient for non-covered days.', '1995-01-01'),
('85', 'Patient Interest Adjustment', 'Credit interest to patient account.', '1995-01-01'),
('89', 'Professional fees removed from charges.', 'Rebill on professional claim form (CMS-1500).', '1995-01-01'),
('90', 'Ingredient cost adjustment.', 'Write off (Pharmacy contract).', '1995-01-01'),
('91', 'Dispensing fee adjustment.', 'Write off (Pharmacy contract).', '1995-01-01'),
('94', 'Processed in Excess of charges.', 'Create negative adjustment/refund.', '1995-01-01'),
('95', 'Plan procedures not followed.', 'Write off or Appeal with proof of compliance.', '1995-01-01'),
('96', 'Non-covered charge(s).', 'Check plan coverage. Bill to patient if allowed.', '1995-01-01'),
('97', 'The benefit for this service is included in the payment/allowance for another service/procedure.', 'Write off (Bundled). DO NOT bill patient.', '1995-01-01'),
('100', 'Payment made to patient/insured/responsible party.', 'Bill patient for full amount (Payment sent to them).', '1995-01-01'),
('101', 'Predetermination: anticipated payment upon completion of services or claim adjudication.', 'No action. Informational only.', '1995-01-01'),
('102', 'Major Medical Adjustment.', 'Transfer balance to Major Medical.', '1995-01-01'),
('103', 'Provider promotional discount.', 'Write off.', '1995-01-01'),
('104', 'Managed care withholding.', 'Track withhold (Receivable). Do not write off.', '1995-01-01'),
('105', 'Tax withholding.', 'Post tax deduction.', '1995-01-01'),
('106', 'Patient payment option/election not in effect.', 'Bill patient.', '1995-01-01'),
('107', 'The related or qualifying claim/service was not identified on this claim.', 'Resubmit with correct linkage to primary service.', '1995-01-01'),
('108', 'Rent/purchase guidelines were not met.', 'Review DME guidelines. Resubmit or bill patient.', '1995-01-01'),
('109', 'Claim/service not covered by this payer/contractor. You must send the claim/service to the correct payer/contractor.', 'Forward claim to correct payer.', '1995-01-01'),
('110', 'Billing date predates service date.', 'Correct billing date and resubmit.', '1995-01-01'),
('111', 'Not covered unless the provider accepts assignment.', 'Accept assignment and resubmit or bill patient.', '1995-01-01'),
('112', 'Service not furnished directly to the patient and/or not documented.', 'Provide documentation or write off.', '1995-01-01'),
('114', 'Procedure/product not approved by the Food and Drug Administration.', 'Bill patient (if ABN) or write off.', '1995-01-01'),
('115', 'Procedure postponed, canceled, or delayed.', 'Write off.', '1995-01-01'),
('116', 'The advance indemnification notice signed by the patient did not comply with requirements.', 'Write off (Invalid ABN).', '1995-01-01'),
('117', 'Transportation is only covered to the closest facility that can provide the necessary care.', 'Bill patient for mileage excess.', '1995-01-01'),
('118', 'ESRD network support adjustment.', 'Write off.', '1995-01-01'),
('119', 'Benefit maximum for this time period or occurrence has been reached.', 'Bill patient.', '1995-01-01'),
('121', 'Indemnification adjustment - compensation for outstanding member responsibility.', 'Post adjustment.', '1995-01-01'),
('122', 'Psychiatric reduction.', 'Write off or Bill patient depending on contract.', '1995-01-01'),
('128', 'Newborn''s services are covered in the mother''s Allowance.', 'Write off (Bundled).', '1997-02-28'),
('129', 'Prior processing information appears incorrect.', 'Review EOB history. Resubmit corrected claim.', '1997-02-28'),
('130', 'Claim submission fee.', 'Write off (Admin fee).', '1997-02-28'),
('131', 'Claim specific negotiated discount.', 'Write off (Contractual).', '1997-02-28'),
('132', 'Prearranged demonstration project adjustment.', 'Write off.', '1997-02-28'),
('133', 'The disposition of this service line is pending further review.', 'Wait for final adjudication. Do not bill yet.', '2014-07-01'),
('134', 'Technical fees removed from charges.', 'Rebill technical component appropriately.', '1998-10-31'),
('135', 'Interim bills cannot be processed.', 'Submit final bill on discharge.', '1998-10-31'),
('136', 'Failure to follow prior payer''s coverage rules.', 'Correct primary claim errors and resubmit.', '1998-10-31'),
('137', 'Regulatory Surcharges, Assessments, Allowances or Health Related Taxes.', 'Post tax adjustment.', '1999-02-28'),
('139', 'Contracted funding agreement - Subscriber is employed by the provider of services.', 'Write off (Employee courtesy).', '1999-06-30'),
('140', 'Patient/Insured health identification number and name do not match.', 'Verify Member ID and Name. Correct and resubmit.', '1999-06-30'),
('142', 'Monthly Medicaid patient liability amount.', 'Collect Spend-down/Liability from patient.', '2000-06-30'),
('143', 'Portion of payment deferred.', 'Track deferral. Do not write off.', '2001-02-28'),
('144', 'Incentive adjustment, e.g. preferred product/service.', 'Post incentive payment.', '2001-06-30'),
('146', 'Diagnosis was invalid for the date(s) of service reported.', 'Check diagnosis effective dates (ICD-9 vs ICD-10). Correct and resubmit.', '2002-06-30'),
('147', 'Provider contracted/negotiated rate expired or not on file.', 'Contact Provider Relations to update fee schedule.', '2002-06-30'),
('148', 'Information from another provider was not provided or was insufficient/incomplete.', 'Obtain records from referring provider and resubmit.', '2002-06-30'),
('149', 'Lifetime benefit maximum has been reached for this service/benefit category.', 'Bill patient.', '2002-10-31'),
('150', 'Payer deems the information submitted does not support this level of service.', 'Appeal with records (Downcoding) or write off difference.', '2002-10-31'),
('151', 'Payment adjusted because the payer deems the information submitted does not support this many/frequency of services.', 'Appeal with medical necessity for frequency.', '2002-10-31'),
('152', 'Payer deems the information submitted does not support this length of service.', 'Appeal with time-stamped records.', '2002-10-31'),
('153', 'Payer deems the information submitted does not support this dosage.', 'Appeal with medication logs/orders.', '2002-10-31'),
('154', 'Payer deems the information submitted does not support this day''s supply.', 'Appeal with prescription info.', '2002-10-31'),
('155', 'Patient refused the service/procedure.', 'Write off or Bill patient depending on circumstance.', '2003-06-30'),
('157', 'Service/procedure was provided as a result of an act of war.', 'Bill patient (Policy Exclusion).', '2003-09-30'),
('158', 'Service/procedure was provided outside of the United States.', 'Bill patient (Policy Exclusion).', '2003-09-30'),
('159', 'Service/procedure was provided as a result of terrorism.', 'Bill patient (Policy Exclusion).', '2003-09-30'),
('160', 'Injury/illness was the result of an activity that is a benefit exclusion.', 'Bill patient.', '2003-09-30'),
('161', 'Provider performance bonus', 'Post bonus payment.', '2004-02-29'),
('163', 'Attachment/other documentation referenced on the claim was not received.', 'Submit required attachment (e.g., operative report).', '2004-06-30'),
('164', 'Attachment/other documentation referenced on the claim was not received in a timely fashion.', 'Appeal with proof of timely submission.', '2004-06-30'),
('166', 'These services were submitted after this payers responsibility for processing claims under this plan ended.', 'Bill new payer or patient.', '2005-02-28'),
('167', 'This (these) diagnosis(es) is (are) not covered.', 'Check LCD/NCD. Bill patient if ABN on file.', '2005-06-30'),
('169', 'Alternate benefit has been provided.', 'Adjust to allowed amount for alternate code.', '2005-06-30'),
('170', 'Payment is denied when performed/billed by this type of provider.', 'Verify credentialing/taxonomy. Resubmit.', '2005-06-30'),
('171', 'Payment is denied when performed/billed by this type of provider in this type of facility.', 'Verify Place of Service vs Provider Type. Resubmit.', '2005-06-30'),
('172', 'Payment is adjusted when performed/billed by a provider of this specialty.', 'Verify specialty code.', '2005-06-30'),
('173', 'Service/equipment was not prescribed by a physician.', 'Obtain valid prescription and appeal.', '2005-06-30'),
('174', 'Service was not prescribed prior to delivery.', 'Write off (Compliance error).', '2005-06-30'),
('175', 'Prescription is incomplete.', 'Correct prescription and appeal.', '2005-06-30'),
('176', 'Prescription is not current.', 'Obtain current prescription and appeal.', '2005-06-30'),
('177', 'Patient has not met the required eligibility requirements.', 'Verify eligibility. Bill patient.', '2005-06-30'),
('178', 'Patient has not met the required spend down requirements.', 'Collect spend-down from patient.', '2005-06-30'),
('179', 'Patient has not met the required waiting requirements.', 'Bill patient.', '2005-06-30'),
('180', 'Patient has not met the required residency requirements.', 'Bill patient.', '2005-06-30'),
('181', 'Procedure code was invalid on the date of service.', 'Use correct CPT/HCPCS for the service year. Resubmit.', '2005-06-30'),
('182', 'Procedure modifier was invalid on the date of service.', 'Use correct modifier. Resubmit.', '2005-06-30'),
('183', 'The referring provider is not eligible to refer the service billed.', 'Verify referring provider credentials.', '2005-06-30'),
('184', 'The prescribing/ordering provider is not eligible to prescribe/order the service billed.', 'Verify ordering provider credentials.', '2005-06-30'),
('185', 'The rendering provider is not eligible to perform the service billed.', 'Verify rendering provider credentials.', '2005-06-30'),
('186', 'Level of care change adjustment.', 'Adjust to authorized level of care.', '2005-06-30'),
('187', 'Consumer Spending Account payments', 'Post payment from HSA/FSA.', '2005-06-30'),
('188', 'This product/procedure is only covered when used according to FDA recommendations.', 'Appeal with FDA label info.', '2005-06-30'),
('189', '''Not otherwise classified'' or ''unlisted'' procedure code was billed.', 'Resubmit with specific CPT or detailed description.', '2005-06-30'),
('190', 'Payment is included in the allowance for a Skilled Nursing Facility (SNF) qualified stay.', 'Bill SNF (Consolidated Billing).', '2005-10-31'),
('192', 'Non standard adjustment code from paper remittance.', 'Manual review required.', '2005-10-31'),
('193', 'Original payment decision is being maintained.', 'No further appeal rights or gather new evidence.', '2006-02-28'),
('194', 'Anesthesia performed by the operating physician.', 'Bill with correct modifier.', '2006-02-28'),
('195', 'Refund issued to an erroneous priority payer for this claim/service.', 'Update COB info.', '2006-02-28'),
('197', 'Precertification/authorization/notification/pre-treatment absent.', 'Write off unless retro-auth obtained. Do not bill patient.', '2006-10-31'),
('198', 'Precertification/notification/authorization/pre-treatment exceeded.', 'Write off excess units.', '2006-10-31'),
('199', 'Revenue code and Procedure code do not match.', 'Correct code mapping and resubmit.', '2006-10-31'),
('200', 'Expenses incurred during lapse in coverage', 'Bill patient.', '2006-10-31'),
('201', 'Patient is responsible for amount of this claim/service through ''set aside arrangement''.', 'Bill patient (Set-Aside funds).', '2006-10-31'),
('202', 'Non-covered personal comfort or convenience services.', 'Bill patient.', '2007-02-28'),
('203', 'Discontinued or reduced service.', 'Write off.', '2007-02-28'),
('204', 'This service/equipment/drug is not covered under the patient''s current benefit plan', 'Bill patient.', '2007-02-28'),
('205', 'Pharmacy discount card processing fee', 'Write off.', '2007-07-09'),
('206', 'National Provider Identifier - missing.', 'Add NPI and resubmit.', '2007-07-09'),
('207', 'National Provider identifier - Invalid format', 'Correct NPI format and resubmit.', '2007-07-09'),
('208', 'National Provider Identifier - Not matched.', 'Verify NPI against payer database. Resubmit.', '2007-07-09'),
('209', 'Per regulatory or other agreement. The provider cannot collect this amount from the patient.', 'Write off. DO NOT bill patient.', '2007-07-09'),
('210', 'Payment adjusted because pre-certification/authorization not received in a timely fashion', 'Write off.', '2007-07-09'),
('211', 'National Drug Codes (NDC) not eligible for rebate, are not covered.', 'Bill patient or write off.', '2007-07-09'),
('212', 'Administrative surcharges are not covered', 'Write off.', '2007-11-05'),
('213', 'Non-compliance with the physician self referral prohibition legislation or payer policy.', 'Write off (Compliance issue).', '2008-01-27'),
('215', 'Based on subrogation of a third party settlement', 'Wait for settlement or bill 3rd party.', '2008-01-27'),
('216', 'Based on the findings of a review organization or the payer''s findings.', 'Review audit findings. Appeal if incorrect.', '2008-01-27'),
('219', 'Based on extent of injury.', 'Review Workers Comp guidelines.', '2008-01-27'),
('222', 'Exceeds the contracted maximum number of hours/days/units by this provider for this period.', 'Write off excess.', '2008-06-01'),
('223', 'Adjustment code for mandated federal, state or local law/regulation.', 'Adjust per mandate.', '2008-06-01'),
('224', 'Patient identification compromised by identity theft.', 'Verify patient identity manually.', '2008-06-01'),
('225', 'Penalty or Interest Payment by Payer', 'Post interest payment.', '2008-06-01'),
('226', 'Information requested from the Billing/Rendering Provider was not provided.', 'Submit requested info.', '2008-09-21'),
('227', 'Information requested from the patient/insured/responsible party was not provided.', 'Contact patient to update payer info.', '2008-09-21'),
('228', 'Denied for failure of this provider... to supply requested information to a previous payer', 'Send info to primary payer first.', '2008-09-21'),
('229', 'Partial charge amount not considered by Medicare due to the initial claim Type of Bill being 12X.', 'Review Medicare MSP rules.', '2009-01-25'),
('231', 'Mutually exclusive procedures cannot be done in the same day/setting.', 'Write off (NCCI edit) or appeal with modifier 59 if applicable.', '2009-07-01'),
('232', 'Institutional Transfer Amount.', 'Adjust DRG payment.', '2009-11-01'),
('233', 'Services/charges related to the treatment of a hospital-acquired condition or preventable medical error.', 'Write off. Do not bill patient.', '2010-01-24'),
('234', 'This procedure is not paid separately.', 'Write off (Bundled).', '2010-01-24'),
('235', 'Sales Tax', 'Post tax.', '2010-06-06'),
('236', 'This procedure... is not compatible with another procedure... provided on the same day.', 'Write off (NCCI edit) or appeal with modifier.', '2011-01-30'),
('237', 'Legislated/Regulatory Penalty.', 'Write off penalty.', '2011-06-05'),
('238', 'Claim spans eligible and ineligible periods of coverage.', 'Split claim dates. Bill patient for ineligible portion.', '2012-03-01'),
('239', 'Claim spans eligible and ineligible periods of coverage. Rebill separate claims.', 'Split claim into two and resubmit.', '2012-03-01'),
('240', 'The diagnosis is inconsistent with the patient''s birth weight.', 'Verify birth weight on claim.', '2012-06-03'),
('241', 'Low Income Subsidy (LIS) Co-payment Amount', 'Collect reduced LIS co-pay.', '2012-06-03'),
('242', 'Services not provided by network/primary care providers.', 'Write off (if HMO) or Bill Patient (if PPO).', '2012-06-03'),
('243', 'Services not authorized by network/primary care providers.', 'Appeal with referral or Write off.', '2012-06-03'),
('245', 'Provider performance program withhold.', 'Track withhold.', '2012-09-30'),
('246', 'This non-payable code is for required reporting only.', 'No action. Informational.', '2012-09-30'),
('247', 'Deductible for Professional service rendered in an Institutional setting.', 'Collect deductible.', '2012-09-30'),
('248', 'Coinsurance for Professional service rendered in an Institutional setting.', 'Collect coinsurance.', '2012-09-30'),
('249', 'This claim has been identified as a readmission.', 'Write off (Bundled into initial stay).', '2012-09-30'),
('250', 'The attachment... received was the incorrect attachment/document.', 'Submit correct attachment.', '2012-09-30'),
('251', 'The attachment... received was incomplete or deficient.', 'Submit complete attachment.', '2012-09-30'),
('252', 'An attachment/other documentation is required to adjudicate this claim/service.', 'Submit required attachment.', '2012-09-30'),
('253', 'Sequestration - reduction in federal payment', 'Write off (Mandatory Federal Reduction). Do not bill patient.', '2013-06-02'),
('254', 'Claim received by the dental plan, but benefits not available... Submit to medical plan.', 'Resubmit to Medical Payer.', '2013-06-02'),
('256', 'Service not payable per managed care contract.', 'Write off.', '2013-06-02'),
('257', 'The disposition of the claim/service is undetermined during the premium payment grace period.', 'Hold claim. Monitor payment status.', '2013-11-01'),
('258', 'Claim/service not covered when patient is in custody/incarcerated.', 'Bill correct government authority.', '2013-11-01'),
('259', 'Additional payment for Dental/Vision service utilization.', 'Post payment.', '2014-01-26'),
('260', 'Processed under Medicaid ACA Enhanced Fee Schedule', 'Post enhanced payment.', '2014-01-26'),
('261', 'The procedure or service is inconsistent with the patient''s history.', 'Review medical history. Appeal with notes.', '2014-06-01'),
('262', 'Adjustment for delivery cost.', 'Write off or Bill patient (if allowed).', '2014-11-01'),
('263', 'Adjustment for shipping cost.', 'Write off or Bill patient (if allowed).', '2014-11-01'),
('264', 'Adjustment for postage cost.', 'Write off or Bill patient (if allowed).', '2014-11-01'),
('265', 'Adjustment for administrative cost.', 'Write off.', '2014-11-01'),
('266', 'Adjustment for compound preparation cost.', 'Write off.', '2014-11-01'),
('267', 'Claim/service spans multiple months.', 'Split claim by month.', '2014-11-01'),
('268', 'The Claim spans two calendar years. Please resubmit one claim per calendar year.', 'Split claim by year and resubmit.', '2014-11-01'),
('269', 'Anesthesia not covered for this service/procedure.', 'Bill patient.', '2015-03-01'),
('270', 'Claim received by the medical plan... Submit... to dental plan.', 'Resubmit to Dental Payer.', '2015-07-01'),
('271', 'Prior contractual reductions related to a current periodic payment', 'Informational adjustment.', '2015-11-01'),
('272', 'Coverage/program guidelines were not met.', 'Bill patient.', '2015-11-01'),
('273', 'Coverage/program guidelines were exceeded.', 'Bill patient.', '2015-11-01'),
('274', 'Fee/Service not payable per patient Care Coordination arrangement.', 'Write off.', '2015-11-01'),
('275', 'Prior payer''s... patient responsibility... not covered.', 'Bill patient for remaining balance.', '2015-11-01'),
('276', 'Services denied by the prior payer(s) are not covered by this payer.', 'Bill patient.', '2015-11-01'),
('277', 'The disposition... is undetermined during the premium payment grace period (SHOP).', 'Hold claim.', '2015-11-01'),
('278', 'Performance program proficiency requirements not met.', 'Write off.', '2016-07-01'),
('279', 'Services not provided by Preferred network providers.', 'Bill patient (Out of Network).', '2016-11-01'),
('280', 'Claim received by the medical plan... Submit... to Pharmacy plan.', 'Resubmit to Pharmacy Payer.', '2017-03-01'),
('281', 'Deductible waived per contractual agreement.', 'Write off deductible.', '2017-07-01'),
('282', 'The procedure/revenue code is inconsistent with the type of bill.', 'Correct Bill Type and resubmit.', '2017-07-01'),
('283', 'Attending provider is not eligible to provide direction of care.', 'Verify provider credentials.', '2017-11-01'),
('284', 'Precertification... number may be valid but does not apply to the billed services.', 'Correct authorization number and resubmit.', '2017-11-01'),
('285', 'Appeal procedures not followed', 'Follow correct appeal protocol.', '2017-11-01'),
('286', 'Appeal time limits not met', 'Write off (Timely filing for appeal).', '2017-11-01'),
('287', 'Referral exceeded', 'Bill patient or write off (depending on contract).', '2017-11-01'),
('288', 'Referral absent', 'Obtain referral or write off.', '2017-11-01'),
('289', 'Services considered under the dental and medical plans, benefits not available.', 'Bill patient.', '2017-11-01'),
('290', 'Claim received by the dental plan... Claim has been forwarded to the patient''s medical plan', 'Wait for Medical plan EOB.', '2017-11-01'),
('291', 'Claim received by the medical plan... Claim has been forwarded to the patient''s dental plan', 'Wait for Dental plan EOB.', '2017-11-01'),
('292', 'Claim received by the medical plan... Claim has been forwarded to the patient''s pharmacy plan', 'Wait for Pharmacy plan EOB.', '2017-11-01'),
('293', 'Payment made to employer.', 'Contact employer for payment.', '2018-05-01'),
('294', 'Payment made to attorney.', 'Contact attorney for payment.', '2017-11-01'),
('295', 'Pharmacy Direct/Indirect Remuneration (DIR)', 'Post DIR fee.', '2018-03-01'),
('296', 'Precertification... number may be valid but does not apply to the provider.', 'Obtain auth for correct provider.', '2018-07-01'),
('297', 'Claim received by the medical plan... Submit... to vision plan.', 'Resubmit to Vision Payer.', '2019-03-01'),
('298', 'Claim received by the medical plan... Claim has been forwarded to the patient''s vision plan', 'Wait for Vision plan EOB.', '2019-03-01'),
('299', 'The billing provider is not eligible to receive payment for the service billed.', 'Verify provider eligibility.', '2019-07-01'),
('300', 'Claim received by the Medical Plan... Claim has been forwarded to... Behavioral Health Plan', 'Wait for BH plan EOB.', '2019-07-01'),
('301', 'Claim received by the Medical Plan... Submit... to Behavioral Health Plan', 'Resubmit to BH Payer.', '2019-07-01'),
('302', 'Precertification... time limit has expired.', 'Appeal with reason for delay or write off.', '2020-11-01'),
('303', 'Prior payer''s... patient responsibility... not covered for Qualified Medicare and Medicaid Beneficiaries.', 'Write off (QMB billing prohibited).', '2021-07-01'),
('304', 'Claim received by the medical plan... Submit... to hearing plan.', 'Resubmit to Hearing Payer.', '2022-03-01'),
('305', 'Claim received by the medical plan... Claim has been forwarded to the patient''s hearing plan', 'Wait for Hearing plan EOB.', '2022-03-01'),
('306', 'Type of bill is inconsistent with the patient status.', 'Correct patient status and resubmit.', '2023-11-01'),
('307', 'Medicare Maximum Fair Price Standard Default Refund Amount Adjustment.', 'Post adjustment (Medicare Negotiation).', '2025-03-01'),
('308', 'Payment is adjusted due to contracted funding agreement between the payer and provider.', 'Write off.', '2025-11-01'),
('A0', 'Patient refund amount.', 'Issue refund to patient.', '1995-01-01'),
('A1', 'Claim/Service denied.', 'Check Remarks code for specific reason.', '1995-01-01'),
('A5', 'Medicare Claim PPS Capital Cost Outlier Amount.', 'Post adjustment.', '1995-01-01'),
('A6', 'Prior hospitalization or 30 day transfer requirement not met.', 'Verify admission requirements.', '1995-01-01'),
('A8', 'Ungroupable DRG.', 'Review coding logic. Resubmit.', '1995-01-01'),
('B1', 'Non-covered visits.', 'Bill patient.', '1995-01-01'),
('B4', 'Late filing penalty.', 'Write off penalty.', '1995-01-01'),
('B7', 'This provider was not certified/eligible to be paid for this procedure/service on this date of service.', 'Verify certification date.', '1995-01-01'),
('B8', 'Alternative services were available, and should have been utilized.', 'Appeal with medical necessity.', '1995-01-01'),
('B9', 'Patient is enrolled in a Hospice.', 'Bill Hospice carrier.', '1995-01-01'),
('B10', 'Allowed amount has been reduced because a component of the basic procedure/test was paid.', 'Write off (Bundled).', '1995-01-01'),
('B11', 'The claim/service has been transferred to the proper payer/processor for processing.', 'Wait for correct payer response.', '1995-01-01'),
('B12', 'Services not documented in patient''s medical records.', 'Amend records if possible. Write off otherwise.', '1995-01-01'),
('B13', 'Previously paid. Payment for this claim/service may have been provided in a previous payment.', 'Check payment history. Void if duplicate.', '1995-01-01'),
('B14', 'Only one visit or consultation per physician per day is covered.', 'Write off or appeal with specific circumstances.', '1995-01-01'),
('B15', 'This service/procedure requires that a qualifying service/procedure be received and covered.', 'Verify primary service payment.', '1995-01-01'),
('B16', '''New Patient'' qualifications were not met.', 'Change to Established Patient code.', '1995-01-01'),
('B20', 'Procedure/service was partially or fully furnished by another provider.', 'Verify split billing rules.', '1995-01-01'),
('B22', 'This payment is adjusted based on the diagnosis.', 'Review diagnosis coding.', '1995-01-01'),
('B23', 'Procedure billed is not authorized per your Clinical Laboratory Improvement Amendment (CLIA) proficiency test.', 'Verify CLIA certification.', '1995-01-01'),
('P1', 'State-mandated Requirement for Property and Casualty.', 'Review State P&C laws.', '2013-11-01'),
('P2', 'Not a work related injury/illness and thus not the liability of the workers'' compensation carrier', 'Bill Health Insurance Plan.', '2013-11-01'),
('P3', 'Workers'' Compensation case settled. Patient is responsible... through ''Medicare set aside''.', 'Bill patient (MSA funds).', '2013-11-01'),
('P4', 'Workers'' Compensation claim adjudicated as non-compensable. This Payer not liable.', 'Bill Health Insurance Plan.', '2013-11-01'),
('P5', 'Based on payer reasonable and customary fees.', 'Write off or Bill patient depending on P&C laws.', '2013-11-01'),
('P6', 'Based on entitlement to benefits.', 'Verify P&C benefit limits.', '2013-11-01'),
('P7', 'The applicable fee schedule/fee database does not contain the billed code.', 'Resubmit with valid P&C code.', '2013-11-01'),
('P8', 'Claim is under investigation.', 'Monitor claim status. Provide requested info.', '2013-11-01'),
('P9', 'No available or correlating CPT/HCPCS code to describe this service.', 'Submit with description/notes.', '2013-11-01'),
('P10', 'Payment reduced to zero due to litigation.', 'Hold claim pending litigation.', '2013-11-01'),
('P11', 'The disposition of the related Property & Casualty claim... is pending due to litigation.', 'Hold claim.', '2013-11-01'),
('P12', 'Workers'' compensation jurisdictional fee schedule adjustment.', 'Write off difference.', '2013-11-01'),
('P13', 'Payment reduced or denied based on workers'' compensation jurisdictional regulations', 'Review jurisdiction rules.', '2013-11-01'),
('P14', 'The Benefit for this Service is included in the payment/allowance for another service/procedure.', 'Write off (Bundled).', '2013-11-01'),
('P15', 'Workers'' Compensation Medical Treatment Guideline Adjustment.', 'Appeal with guidelines proof.', '2013-11-01'),
('P16', 'Medical provider not authorized/certified to provide treatment to injured workers in this jurisdiction.', 'Verify WC certification.', '2013-11-01'),
('P17', 'Referral not authorized by attending physician per regulatory requirement.', 'Obtain authorized referral.', '2013-11-01'),
('P18', 'Procedure is not listed in the jurisdiction fee schedule. An allowance has been made.', 'Adjust to allowed amount.', '2013-11-01'),
('P19', 'Procedure has a relative value of zero in the jurisdiction fee schedule.', 'Write off.', '2013-11-01'),
('P20', 'Service not paid under jurisdiction allowed outpatient facility fee schedule.', 'Write off.', '2013-11-01'),
('P21', 'Payment denied based on the Medical Payments Coverage (MPC) regulations.', 'Review MPC rules.', '2013-11-01'),
('P22', 'Payment adjusted based on the Medical Payments Coverage (MPC) regulations.', 'Adjust per MPC rules.', '2013-11-01'),
('P23', 'Medical Payments Coverage (MPC)... jurisdictional fee schedule adjustment.', 'Write off.', '2013-11-01'),
('P24', 'Payment adjusted based on Preferred Provider Organization (PPO).', 'Write off contractual amount.', '2017-11-01'),
('P25', 'Payment adjusted based on Medical Provider Network (MPN).', 'Write off contractual amount.', '2017-11-01'),
('P26', 'Payment adjusted based on Voluntary Provider network (VPN).', 'Write off contractual amount.', '2017-11-01'),
('P27', 'Payment denied based on the Liability Coverage Benefits jurisdictional regulations', 'Review Liability rules.', '2017-11-01'),
('P28', 'Payment adjusted based on the Liability Coverage Benefits jurisdictional regulations', 'Adjust per Liability rules.', '2017-11-01'),
('P29', 'Liability Benefits jurisdictional fee schedule adjustment.', 'Write off.', '2017-11-01'),
('P30', 'Payment denied for exacerbation when supporting documentation was not complete.', 'Submit complete documentation.', '2020-11-01'),
('P31', 'Payment denied for exacerbation when treatment exceeds time allowed.', 'Write off or Appeal.', '2020-11-01'),
('P32', 'Payment adjusted due to Apportionment.', 'Adjust per apportionment %.', '2022-08-01');

-- Insert RARC Codes
INSERT INTO rarc_codes (code, description, start_date) VALUES
('M1', 'X-ray not taken within the past 12 months or near enough to the start of treatment.', '1997-01-01'),
('M2', 'Not paid separately when the patient is an inpatient.', '1997-01-01'),
('M3', 'Equipment is the same or similar to equipment already being used.', '1997-01-01'),
('M4', 'Alert: This is the last monthly installment payment for this durable medical equipment.', '1997-01-01'),
('M5', 'Monthly rental payments can continue until the earlier of the 15th month from the first rental month, or the month when the equipment is no longer needed.', '1997-01-01'),
('M6', 'Alert: You must furnish and service this item for any period of medical need for the remainder of the reasonable useful lifetime of the equipment.', '1997-01-01'),
('M7', 'No rental payments after the item is purchased, returned or after the total of issued rental payments equals the purchase price.', '1997-01-01'),
('M8', 'We do not accept blood gas tests results when the test was conducted by a medical supplier or taken while the patient is on oxygen.', '1997-01-01'),
('M9', 'Alert: This is the tenth rental month. You must offer the patient the choice of changing the rental to a purchase agreement.', '1997-01-01'),
('M10', 'Equipment purchases are limited to the first or the tenth month of medical necessity.', '1997-01-01'),
('M11', 'DME, orthotics and prosthetics must be billed to the DME carrier who services the patient''s zip code.', '1997-01-01'),
('M12', 'Diagnostic tests performed by a physician must indicate whether purchased services are included on the claim.', '1997-01-01'),
('M13', 'Only one initial visit is covered per specialty per medical group.', '1997-01-01'),
('M14', 'No separate payment for an injection administered during an office visit, and no payment for a full office visit if the patient only received an injection.', '1997-01-01'),
('M15', 'Separately billed services/tests have been bundled as they are considered components of the same procedure. Separate payment is not allowed.', '1997-01-01'),
('M16', 'Alert: Please see our web site, mailings, or bulletins for more details concerning this policy/procedure/decision.', '1997-01-01'),
('M17', 'Alert: Payment approved as you did not know, and could not reasonably have been expected to know, that this would not normally have been covered for this patient. In the future, you will be liable for charges for the same service(s) under the same or similar conditions.', '1997-01-01'),
('M18', 'Certain services may be approved for home use. Neither a hospital nor a Skilled Nursing Facility (SNF) is considered to be a patient''s home.', '1997-01-01'),
('M19', 'Missing oxygen certification/re-certification.', '1997-01-01'),
('M20', 'Missing/incomplete/invalid HCPCS.', '1997-01-01'),
('M21', 'Missing/incomplete/invalid place of residence for this service/item provided in a home.', '1997-01-01'),
('M22', 'Missing/incomplete/invalid number of miles traveled.', '1997-01-01'),
('M23', 'Missing invoice.', '1997-01-01'),
('M24', 'Missing/incomplete/invalid number of doses per vial.', '1997-01-01'),
('M25', 'The information furnished does not substantiate the need for this level of service. If you believe the service should have been fully covered as billed, or if you did not know and could not reasonably have been expected to know that we would not pay for this level of service, or if you notified the patient in writing in advance that we would not pay for this level of service and he/she agreed in writing to pay, ask us to review your claim within 120 days of the date of this notice. If you do not request an appeal, we will, upon application from the patient, reimburse him/her for the amount you have collected from him/her in excess of any deductible and coinsurance amounts. We will recover the reimbursement from you as an overpayment.', '1997-01-01'),
('M26', 'The information furnished does not substantiate the need for this level of service. If you have collected any amount from the patient for this level of service/any amount that exceeds the limiting charge for the less extensive service, the law requires you to refund that amount to the patient within 30 days of receiving this notice.', '1997-01-01'),
('M27', 'Alert: The patient has been relieved of liability of payment of these items and services under the limitation of liability provision of the law. The provider is ultimately liable for the patient''s waived charges, including any charges for coinsurance, since the items or services were not reasonable and necessary or constituted custodial care, and you knew or could reasonably have been expected to know, that they were not covered. You may appeal this determination. You may ask for an appeal regarding both the coverage determination and the issue of whether you exercised due care. The appeal request must be filed within 120 days of the date you receive this notice. You must make the request through this office.', '1997-01-01'),
('M28', 'This does not qualify for payment under Part B when Part A coverage is exhausted or not otherwise available.', '1997-01-01'),
('M29', 'Missing operative note/report.', '1997-01-01'),
('M30', 'Missing pathology report.', '1997-01-01'),
('M31', 'Missing radiology report.', '1997-01-01'),
('M32', 'Alert: This is a conditional payment made pending a decision on this service by the patient''s primary payer. This payment may be subject to refund upon your receipt of any additional payment for this service from another payer. You must contact this office immediately upon receipt of an additional payment for this service.', '1997-01-01'),
('M36', 'This is the 11th rental month. We cannot pay for this until you indicate that the patient has been given the option of changing the rental to a purchase.', '1997-01-01'),
('M37', 'Not covered when the patient is under age 35.', '1997-01-01'),
('M38', 'Alert: The patient is liable for the charges for this service as they were informed in writing before the service was furnished that we would not pay for it and the patient agreed to be responsible for the charges.', '1997-01-01'),
('M39', 'Alert: The patient is not liable for payment of this service as the advance notice of non-coverage you provided the patient did not comply with program requirements.', '1997-01-01'),
('M40', 'Claim must be assigned and must be filed by the practitioner''s employer.', '1997-01-01'),
('M41', 'We do not pay for this as the patient has no legal obligation to pay for this.', '1997-01-01'),
('M42', 'The medical necessity form must be personally signed by the attending physician.', '1997-01-01'),
('M44', 'Missing/incomplete/invalid condition code.', '1997-01-01'),
('M45', 'Missing/incomplete/invalid occurrence code(s).', '1997-01-01'),
('M46', 'Missing/incomplete/invalid occurrence span code(s).', '1997-01-01'),
('M47', 'Missing/incomplete/invalid Payer Claim Control Number. Other terms exist for this element including, but not limited to, Internal Control Number (ICN), Claim Control Number (CCN), Document Control Number (DCN).', '1997-01-01'),
('M49', 'Missing/incomplete/invalid value code(s) or amount(s).', '1997-01-01'),
('M50', 'Missing/incomplete/invalid revenue code(s).', '1997-01-01'),
('M51', 'Missing/incomplete/invalid procedure code(s).', '1997-01-01'),
('M52', 'Missing/incomplete/invalid ''from'' date(s) of service.', '1997-01-01'),
('M53', 'Missing/incomplete/invalid days or units of service.', '1997-01-01'),
('M54', 'Missing/incomplete/invalid total charges.', '1997-01-01'),
('M55', 'We do not pay for self-administered anti-emetic drugs that are not administered with a covered oral anti-cancer drug.', '1997-01-01'),
('M56', 'Missing/incomplete/invalid payer identifier.', '1997-01-01'),
('M59', 'Missing/incomplete/invalid ''to'' date(s) of service.', '1997-01-01'),
('M60', 'Missing Certificate of Medical Necessity.', '1997-01-01'),
('M61', 'We cannot pay for this as the approval period for the FDA clinical trial has expired.', '1997-01-01'),
('M62', 'Missing/incomplete/invalid treatment authorization code.', '1997-01-01'),
('M64', 'Missing/incomplete/invalid other diagnosis.', '1997-01-01'),
('M65', 'One interpreting physician charge can be submitted per claim when a purchased diagnostic test is indicated. Please submit a separate claim for each interpreting physician.', '1997-01-01'),
('M66', 'Our records indicate that you billed diagnostic tests subject to price limitations and the procedure code submitted includes a professional component. Only the technical component is subject to price limitations. Please submit the technical and professional components of this service as separate line items.', '1997-01-01'),
('M67', 'Missing/incomplete/invalid other procedure code(s).', '1997-01-01'),
('M69', 'Paid at the regular rate as you did not submit documentation to justify the modified procedure code.', '1997-01-01'),
('M70', 'Alert: The NDC code submitted for this service was translated to a HCPCS code for processing, but please continue to submit the NDC on future claims for this item.', '1997-01-01'),
('M71', 'Total payment reduced due to overlap of tests billed.', '1997-01-01'),
('M73', 'The HPSA/Physician Scarcity bonus can only be paid on the professional component of this service. Rebill as separate professional and technical components.', '1997-01-01'),
('M74', 'This service does not qualify for a HPSA/Physician Scarcity bonus payment.', '1997-01-01'),
('M75', 'Multiple automated multichannel tests performed on the same day combined for payment.', '1997-01-01'),
('M76', 'Missing/incomplete/invalid diagnosis or condition.', '1997-01-01'),
('M77', 'Missing/incomplete/invalid/inappropriate place of service.', '1997-01-01'),
('M79', 'Missing/incomplete/invalid charge.', '1997-01-01'),
('M80', 'Not covered when performed during the same session/date as a previously processed service for the patient.', '1997-01-01'),
('M81', 'You are required to code to the highest level of specificity.', '1997-01-01'),
('M82', 'Service is not covered when patient is under age 50.', '1997-01-01'),
('M83', 'Service is not covered unless the patient is classified as at high risk.', '1997-01-01'),
('M84', 'Medical code sets used must be the codes in effect at the time of service.', '1997-01-01'),
('M85', 'Subjected to review of physician evaluation and management services.', '1997-01-01'),
('M86', 'Service denied because payment already made for same/similar procedure within set time frame.', '1997-01-01'),
('M87', 'Claim/service(s) subjected to CFO-CAP prepayment review.', '1997-01-01'),
('M89', 'Not covered more than once under age 40.', '1997-01-01'),
('M90', 'Not covered more than once in a 12 month period.', '1997-01-01'),
('M91', 'Lab procedures with different CLIA certification numbers must be billed on separate claims.', '1997-01-01'),
('M93', 'Information supplied supports a break in therapy. A new capped rental period began with delivery of this equipment.', '1997-01-01'),
('M94', 'Information supplied does not support a break in therapy. A new capped rental period will not begin.', '1997-01-01'),
('M95', 'Services subjected to Home Health Initiative medical review/cost report audit.', '1997-01-01'),
('M96', 'The technical component of a service furnished to an inpatient may only be billed by that inpatient facility. You must contact the inpatient facility for technical component reimbursement. If not already billed, you should bill us for the professional component only.', '1997-01-01'),
('M97', 'Not paid to practitioner when provided to patient in this place of service. Payment included in the reimbursement issued the facility.', '1997-01-01'),
('M99', 'Missing/incomplete/invalid Universal Product Number/Serial Number.', '1997-01-01'),
('M100', 'We do not pay for an oral anti-emetic drug that is not administered for use immediately before, at, or within 48 hours of administration of a covered chemotherapy drug.', '1997-01-01'),
('M102', 'Service not performed on equipment approved by the FDA for this purpose.', '1997-01-01'),
('M103', 'Information supplied supports a break in therapy. However, the medical information we have for this patient does not support the need for this item as billed. We have approved payment for this item at a reduced level, and a new capped rental period will begin with the delivery of this equipment.', '1997-01-01'),
('M104', 'Information supplied supports a break in therapy. A new capped rental period will begin with delivery of the equipment. This is the maximum approved under the fee schedule for this item or service.', '1997-01-01'),
('M105', 'Information supplied does not support a break in therapy. The medical information we have for this patient does not support the need for this item as billed. We have approved payment for this item at a reduced level, and a new capped rental period will not begin.', '1997-01-01'),
('M107', 'Payment reduced as 90-day rolling average hematocrit for ESRD patient exceeded 36.5%.', '1997-01-01'),
('M109', 'We have provided you with a bundled payment for a teleconsultation. You must send 25 percent of the teleconsultation payment to the referring practitioner.', '1997-01-01'),
('M111', 'We do not pay for chiropractic manipulative treatment when the patient refuses to have an x-ray taken.', '1997-01-01'),
('M112', 'Reimbursement for this item is based on the single payment amount required under the DMEPOS Competitive Bidding Program for the area where the patient resides.', '1997-01-01'),
('M113', 'Our records indicate that this patient began using this item/service prior to the current contract period for the DMEPOS Competitive Bidding Program.', '1997-01-01'),
('M114', 'This service was processed in accordance with rules and guidelines under the DMEPOS Competitive Bidding Program or a Demonstration Project. For more information regarding these projects, contact your local contractor.', '1997-01-01'),
('M115', 'This item is denied when provided to this patient by a non-contract or non-demonstration supplier.', '1997-01-01'),
('M116', 'Processed under a demonstration project or program. Project or program is ending and additional services may not be paid under this project or program.', '1997-01-01'),
('M117', 'Not covered unless submitted via electronic claim.', '1997-01-01'),
('M119', 'Missing/incomplete/invalid/ deactivated/withdrawn National Drug Code (NDC).', '1997-01-01'),
('M121', 'We pay for this service only when performed with a covered cryosurgical ablation.', '1997-01-01'),
('M122', 'Missing/incomplete/invalid level of subluxation.', '1997-01-01'),
('M123', 'Missing/incomplete/invalid name, strength, or dosage of the drug furnished.', '1997-01-01'),
('M124', 'Missing indication of whether the patient owns the equipment that requires the part or supply.', '1997-01-01'),
('M125', 'Missing/incomplete/invalid information on the period of time for which the service/supply/equipment will be needed.', '1997-01-01'),
('M126', 'Missing/incomplete/invalid individual lab codes included in the test.', '1997-01-01'),
('M127', 'Missing patient medical record for this service.', '1997-01-01'),
('M129', 'Missing/incomplete/invalid indicator of x-ray availability for review.', '1997-01-01'),
('M130', 'Missing invoice or statement certifying the actual cost of the lens, less discounts, and/or the type of intraocular lens used.', '1997-01-01'),
('M131', 'Missing physician financial relationship form.', '1997-01-01'),
('M132', 'Missing pacemaker registration form.', '1997-01-01'),
('M133', 'Claim did not identify who performed the purchased diagnostic test or the amount you were charged for the test.', '1997-01-01'),
('M134', 'Performed by a facility/supplier in which the provider has a financial interest.', '1997-01-01'),
('M135', 'Missing/incomplete/invalid plan of treatment.', '1997-01-01'),
('M136', 'Missing/incomplete/invalid indication that the service was supervised or evaluated by a physician.', '1997-01-01'),
('M137', 'Part B coinsurance under a demonstration project or pilot program.', '1997-01-01'),
('M138', 'Patient identified as a demonstration participant but the patient was not enrolled in the demonstration at the time services were rendered. Coverage is limited to demonstration participants.', '1997-01-01'),
('M139', 'Denied services exceed the coverage limit for the demonstration.', '1997-01-01'),
('M141', 'Missing physician certified plan of care.', '1997-01-01'),
('M142', 'Missing American Diabetes Association Certificate of Recognition.', '1997-01-01'),
('M143', 'The provider must update license information with the payer.', '1997-01-01'),
('M144', 'Pre-/post-operative care payment is included in the allowance for the surgery/procedure.', '1997-01-01'),
('MA01', 'Alert: If you do not agree with what we approved for these services, you may appeal our decision. To make sure that we are fair to you, we require another individual that did not process your initial claim to conduct the appeal. However, in order to be eligible for an appeal, you must write to us within 120 days of the date you received this notice, unless you have a good reason for being late.', '1997-01-01'),
('MA02', 'Alert: If you do not agree with this determination, you have the right to appeal. You must file a written request for an appeal within 180 days of the date you receive this notice.', '1997-01-01'),
('MA04', 'Secondary payment cannot be considered without the identity of or payment information from the primary payer. The information was either not reported or was illegible.', '1997-01-01'),
('MA07', 'Alert: The claim information has also been forwarded to Medicaid for review.', '1997-01-01'),
('MA08', 'Alert: Claim information was not forwarded because the supplemental coverage is not with a Medigap plan, or you do not participate in Medicare.', '1997-01-01'),
('MA09', 'Alert: Claim submitted as unassigned but processed as assigned in accordance with our current assignment/participation agreement.', '1997-01-01'),
('MA10', 'Alert: The patient''s payment was in excess of the amount owed. You must refund the overpayment to the patient.', '1997-01-01'),
('MA12', 'You have not established that you have the right under the law to bill for services furnished by the person(s) that furnished this (these) service(s).', '1997-01-01'),
('MA13', 'Alert: You may be subject to penalties if you bill the patient for amounts not reported with the PR (patient responsibility) group code.', '1997-01-01'),
('MA14', 'Alert: The patient is a member of an employer-sponsored prepaid health plan. Services from outside that health plan are not covered. However, as you were not previously notified of this, we are paying this time. In the future, we will not pay you for non-plan services.', '1997-01-01'),
('MA15', 'Alert: Your claim has been separated to expedite handling. You will receive a separate notice for the other services reported.', '1997-01-01'),
('MA16', 'The patient is covered by the Black Lung Program. Send this claim to the Department of Labor, Federal Black Lung Program, P.O. Box 828, Lanham-Seabrook MD 20703.', '1997-01-01'),
('MA17', 'We are the primary payer and have paid at the primary rate. You must contact the patient''s other insurer to refund any excess it may have paid due to its erroneous primary payment.', '1997-01-01'),
('MA18', 'Alert: The claim information is also being forwarded to the patient''s supplemental insurer. Send any questions regarding supplemental benefits to them.', '1997-01-01'),
('MA19', 'Alert: Information was not sent to the Medigap insurer due to incorrect/invalid information you submitted concerning that insurer. Please verify your information and submit your secondary claim directly to that insurer.', '1997-01-01'),
('MA20', 'Skilled Nursing Facility (SNF) stay not covered when care is primarily related to the use of an urethral catheter for convenience or the control of incontinence.', '1997-01-01'),
('MA21', 'SSA records indicate mismatch with name and sex.', '1997-01-01'),
('MA22', 'Payment of less than $1.00 suppressed.', '1997-01-01'),
('MA23', 'Demand bill approved as result of medical review.', '1997-01-01'),
('MA24', 'Christian Science Sanitarium/ Skilled Nursing Facility (SNF) bill in the same benefit period.', '1997-01-01'),
('MA25', 'A patient may not elect to change a hospice provider more than once in a benefit period.', '1997-01-01'),
('MA26', 'Alert: Our records indicate that you were previously informed of this rule.', '1997-01-01'),
('MA27', 'Missing/incomplete/invalid entitlement number or name shown on the claim.', '1997-01-01'),
('MA28', 'Alert: Receipt of this notice by a physician or supplier who did not accept assignment is for information only and does not make the physician or supplier a party to the determination. No additional rights to appeal this decision, above those rights already provided for by regulation/instruction, are conferred by receipt of this notice.', '1997-01-01'),
('MA30', 'Missing/incomplete/invalid type of bill.', '1997-01-01'),
('MA31', 'Missing/incomplete/invalid beginning and ending dates of the period billed.', '1997-01-01'),
('MA32', 'Missing/incomplete/invalid number of covered days during the billing period.', '1997-01-01'),
('MA33', 'Missing/incomplete/invalid non-covered days during the billing period.', '1997-01-01'),
('MA34', 'Missing/incomplete/invalid number of coinsurance days during the billing period.', '1997-01-01'),
('MA35', 'Missing/incomplete/invalid number of lifetime reserve days.', '1997-01-01'),
('MA36', 'Missing/incomplete/invalid patient name.', '1997-01-01'),
('MA37', 'Missing/incomplete/invalid patient''s address.', '1997-01-01'),
('MA39', 'Missing/incomplete/invalid gender.', '1997-01-01'),
('MA40', 'Missing/incomplete/invalid admission date.', '1997-01-01'),
('MA41', 'Missing/incomplete/invalid admission type.', '1997-01-01'),
('MA42', 'Missing/incomplete/invalid admission source.', '1997-01-01'),
('MA43', 'Missing/incomplete/invalid patient status.', '1997-01-01'),
('MA44', 'Alert: No appeal rights. Adjudicative decision based on law.', '1997-01-01'),
('MA45', 'Alert: As previously advised, a portion or all of your payment is being held in a special account.', '1997-01-01'),
('MA46', 'Alert: The new information was considered but additional payment will not be issued.', '1997-01-01'),
('MA47', 'Our records show you have opted out of Medicare, agreeing with the patient not to bill Medicare for services/tests/supplies furnished. As result, we cannot pay this claim. The patient is responsible for payment.', '1997-01-01'),
('MA48', 'Missing/incomplete/invalid name or address of responsible party or primary payer.', '1997-01-01'),
('MA50', 'Missing/incomplete/invalid Investigational Device Exemption number or Clinical Trial number.', '1997-01-01'),
('MA53', 'Missing/incomplete/invalid Competitive Bidding Demonstration Project identification.', '1997-01-01'),
('MA54', 'Physician certification or election consent for hospice care not received timely.', '1997-01-01'),
('MA55', 'Not covered as patient received medical health care services, automatically revoking his/her election to receive religious non-medical health care services.', '1997-01-01'),
('MA56', 'Our records show you have opted out of Medicare, agreeing with the patient not to bill Medicare for services/tests/supplies furnished. As result, we cannot pay this claim. The patient is responsible for payment, but under Federal law, you cannot charge the patient more than the limiting charge amount.', '1997-01-01'),
('MA57', 'Patient submitted written request to revoke his/her election for religious non-medical health care services.', '1997-01-01'),
('MA58', 'Missing/incomplete/invalid release of information indicator.', '1997-01-01'),
('MA59', 'Alert: The patient overpaid you for these services. You must issue the patient a refund within 30 days for the difference between his/her payment and the total amount shown as patient responsibility on this notice.', '1997-01-01'),
('MA60', 'Missing/incomplete/invalid patient relationship to insured.', '1997-01-01'),
('MA61', 'Missing/incomplete/invalid social security number.', '1997-01-01'),
('MA62', 'Alert: This is a telephone review decision.', '1997-01-01'),
('MA63', 'Missing/incomplete/invalid principal diagnosis.', '1997-01-01'),
('MA64', 'Our records indicate that we should be the third payer for this claim. We cannot process this claim until we have received payment information from the primary and secondary payers.', '1997-01-01'),
('MA65', 'Missing/incomplete/invalid admitting diagnosis.', '1997-01-01'),
('MA66', 'Missing/incomplete/invalid principal procedure code.', '1997-01-01'),
('MA67', 'Alert: Correction to a prior claim.', '1997-01-01'),
('MA68', 'Alert: We did not crossover this claim because the secondary insurance information on the claim was incomplete. Please supply complete information or use the PLANID of the insurer to assure correct and timely routing of the claim.', '1997-01-01'),
('MA69', 'Missing/incomplete/invalid remarks.', '1997-01-01'),
('MA70', 'Missing/incomplete/invalid provider representative signature.', '1997-01-01'),
('MA71', 'Missing/incomplete/invalid provider representative signature date.', '1997-01-01'),
('MA72', 'Alert: The patient overpaid you for these assigned services. You must issue the patient a refund within 30 days for the difference between his/her payment to you and the total of the amount shown as patient responsibility and as paid to the patient on this notice.', '1997-01-01'),
('MA73', 'Informational remittance associated with a Medicare demonstration. No payment issued under fee-for-service Medicare as patient has elected managed care.', '1997-01-01'),
('MA74', 'Alert: This payment replaces an earlier payment for this claim that was either lost, damaged or returned.', '1997-01-01'),
('MA75', 'Missing/incomplete/invalid patient or authorized representative signature.', '1997-01-01'),
('MA76', 'Missing/incomplete/invalid provider identifier for home health agency or hospice when physician is performing care plan oversight services.', '1997-01-01'),
('MA77', 'Alert: The patient overpaid you. You must issue the patient a refund within 30 days for the difference between the patient''s payment less the total of our and other payer payments and the amount shown as patient responsibility on this notice.', '1997-01-01'),
('MA79', 'Billed in excess of interim rate.', '1997-01-01'),
('MA80', 'Informational notice. No payment issued for this claim with this notice. Payment issued to the hospital by its intermediary for all services for this encounter under a demonstration project.', '1997-01-01'),
('MA81', 'Missing/incomplete/invalid provider/supplier signature.', '1997-01-01'),
('MA83', 'Did not indicate whether we are the primary or secondary payer.', '1997-01-01'),
('MA84', 'Patient identified as participating in the National Emphysema Treatment Trial but our records indicate that this patient is either not a participant, or has not yet been approved for this phase of the study. Contact Johns Hopkins University, the study coordinator, to resolve if there was a discrepancy.', '1997-01-01'),
('MA88', 'Missing/incomplete/invalid insured''s address and/or telephone number for the primary payer.', '1997-01-01'),
('MA89', 'Missing/incomplete/invalid patient''s relationship to the insured for the primary payer.', '1997-01-01'),
('MA90', 'Missing/incomplete/invalid employment status code for the primary insured.', '1997-01-01'),
('MA91', 'Alert: This determination is the result of the appeal you filed.', '1997-01-01'),
('MA92', 'Missing plan information for other insurance.', '1997-01-01'),
('MA93', 'Non-PIP (Periodic Interim Payment) claim.', '1997-01-01'),
('MA94', 'Did not enter the statement ''Attending physician not hospice employee'' on the claim form to certify that the rendering physician is not an employee of the hospice.', '1997-01-01'),
('MA96', 'Claim rejected. Coded as a Medicare Managed Care Demonstration but patient is not enrolled in a Medicare managed care plan.', '1997-01-01'),
('MA97', 'Missing/incomplete/invalid Medicare Managed Care Demonstration contract number or clinical trial registry number.', '1997-01-01'),
('MA99', 'Missing/incomplete/invalid Medigap information.', '1997-01-01'),
('MA100', 'Missing/incomplete/invalid date of current illness or symptoms.', '1997-01-01'),
('MA103', 'Hemophilia Add On.', '1997-01-01'),
('MA106', 'PIP (Periodic Interim Payment) claim.', '1997-01-01'),
('MA107', 'Paper claim contains more than three separate data items in field 19.', '1997-01-01'),
('MA108', 'Paper claim contains more than one data item in field 23.', '1997-01-01'),
('MA109', 'Claim processed in accordance with ambulatory surgical guidelines.', '1997-01-01'),
('MA110', 'Missing/incomplete/invalid information on whether the diagnostic test(s) were performed by an outside entity or if no purchased tests are included on the claim.', '1997-01-01'),
('MA111', 'Missing/incomplete/invalid purchase price of the test(s) and/or the performing laboratory''s name and address.', '1997-01-01'),
('MA112', 'Missing/incomplete/invalid group practice information.', '1997-01-01'),
('MA113', 'Incomplete/invalid taxpayer identification number (TIN) submitted by you per the Internal Revenue Service. Your claims cannot be processed without your correct TIN, and you may not bill the patient pending correction of your TIN. There are no appeal rights for unprocessable claims, but you may resubmit this claim after you have notified this office of your correct TIN.', '1997-01-01'),
('MA114', 'Missing/incomplete/invalid information on where the services were furnished.', '1997-01-01'),
('MA115', 'Missing/incomplete/invalid physical location (name and address, or PIN) where the service(s) were rendered in a Health Professional Shortage Area (HPSA).', '1997-01-01'),
('MA116', 'Did not complete the statement ''Homebound'' on the claim to validate whether laboratory services were performed at home or in an institution.', '1997-01-01'),
('MA117', 'This claim has been assessed a $1.00 user fee.', '1997-01-01'),
('MA118', 'Alert: No Medicare payment issued for this claim for services or supplies furnished to a Medicare-eligible veteran through a facility of the Department of Veterans Affairs. Coinsurance and/or deductible are applicable.', '1997-01-01'),
('MA120', 'Missing/incomplete/invalid CLIA certification number.', '1997-01-01'),
('MA121', 'Missing/incomplete/invalid x-ray date.', '1997-01-01'),
('MA122', 'Missing/incomplete/invalid initial treatment date.', '1997-01-01'),
('MA123', 'Your center was not selected to participate in this study, therefore, we cannot pay for these services.', '1997-01-01'),
('MA125', 'Per legislation governing this program, payment constitutes payment in full.', '1997-01-01'),
('MA126', 'Pancreas transplant not covered unless kidney transplant performed.', '2001-10-12'),
('MA128', 'Missing/incomplete/invalid FDA approval number.', '2001-10-12'),
('MA130', 'Your claim contains incomplete and/or invalid information, and no appeal rights are afforded because the claim is unprocessable. Please submit a new claim with the complete/correct information.', '2001-10-12'),
('MA131', 'Physician already paid for services in conjunction with this demonstration claim. You must have the physician withdraw that claim and refund the payment before we can process your claim.', '2001-10-12'),
('MA132', 'Adjustment to the pre-demonstration rate.', '2001-10-12'),
('MA133', 'Claim overlaps inpatient stay. Rebill only those services rendered outside the inpatient stay.', '2001-10-12'),
('MA134', 'Missing/incomplete/invalid provider number of the facility where the patient resides.', '2001-10-12');
